#!@execline@/bin/execlineb -Ws1

# SPDX-FileCopyrightText: 2024 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: GLWTPL

foreground { printf "%-5s : %s\n" BEGIN RC.INIT }

s6-envdir -fn @s6ContainerEnv@

define exitcode /run/s6-linux-init-container-results/exitcode
if { rm -rf $exitcode }
if { touch $exitcode }

foreground { s6-rc-init -c @s6DB@ /run/service }
maybedie

foreground { s6-rc -v2 -u -t 60000 -- change $1 }
maybedie

printf "%-5s : %s\n" END RC.INIT
